exports.navlinks = ["home", "about", "menu", "contact"];
exports.menuItems = [
  {
    id: "73628jdd",
    category: "hot coffee and tea",
    name: "Americano",
    image: "hot-americano.png",
    price: 3.75,
    slug: "americano",
    stock: 12,
  },
  {
    id: "34628axd",
    category: "hot coffee and tea",
    name: "Expresso",
    image: "hot-expresso.png",
    price: 3.5,
    slug: "expresso",
    stock: 8,
  },
  {
    id: "24a28acd",
    category: "hot coffee and tea",
    name: "Latte",
    image: "hot-latte.png",
    price: 4.5,
    slug: "latte",
    stock: 7,
  },
  {
    id: "34628axd",
    category: "hot coffee and tea",
    name: "Hot tea",
    image: "hot-tea-earl-grey.png",
    description: "earl grey, lemon ginger, mint",
    price: 4.5,
    slug: "hot-tea",
    stock: 10,
  },
  {
    id: "14628eac",
    category: "breakfast and lunch",
    name: "Bacon scramble",
    image: "bacon-scrambled-egg.jpg",
    description: "aged chedar, onion with toasted country bread",
    price: 10,
    slug: "bacon-scramble",
    stock: 8,
  },
  {
    id: "2e624eac",
    category: "breakfast and lunch",
    name: "Avocado toast with egg",
    image: "avocado-toast with-egg.png",
    description: "chili honey, stoked salt on country bread",
    price: 9,
    slug: "avocado-toast-with-egg",
    stock: 8,
  },
  {
    id: "2e622ebc",
    category: "other hot drinks",
    name: "chai Latte",
    image: "chai-latte-tea.png",

    price: 4.5,
    slug: "chai-latte",
    stock: 7,
  },
  {
    id: "2e622ebc",
    category: "iced coffee and tea",
    name: "cold brew",
    image: "cold-brew.png",

    price: 4.25,
    slug: "cold-brew",
    stock: 11,
  },
  {
    id: "2b612ebc",
    category: "iced coffee and tea",
    name: "iced green tea",
    image: "iced-green-tea.png",
    price: 4,
    slug: "iced-green-tea",
    stock: 8,
  },
  {
    id: "2b652abd",
    category: "bakery",
    name: "double chocolate brownie",
    image: "double-chocolate-brownie.png",
    price: 4,
    slug: "double-chocolate-brownie",
    stock: 13,
  },
  {
    id: "2b342acd",
    category: "bakery",
    name: "cinnamon roll",
    image: "cinnamon-roll.png",

    price: 4,
    slug: "cinnamon-roll",
    stock: 14,
  },
  {
    id: "2ba29ace",
    category: "bakery",
    name: "blueberry muffin",
    image: "blueberry-muffin.jpg",
    price: 3,
    slug: "blueberry-muffin",
    stock: 10,
  },
];

exports.milks = [
  "almond milk",
  "soy milk",
  "skim Milk",
  "oat milk",
  "half & half",
  "whole milk",
];

exports.flavors = [
  "French Vanilla",
  "Hazelnut",
  "Pumpkin Spice",
  "Mocha",
  "Peppermint",
  "Cinnamon",
  "Caramel",
];
