module.exports = {
  OPEN_CART: "OPEN_CART",
  CLOSE_CART: "CLOSE_CART",
  OPEN_PANEL: "OPEN_PANEL",
  CLOSE_PANEL: "CLOSE_PANEL",
  SET_PANEL_POS: "SET_PANEL_POS",
  SET_CURRENT_LIST_ITEM: "SET_CURRENT_LIST_ITEM",
  SET_CURRENT_ELEMENT_INDEX: "SET_CURRENT_ELEMENT_INDEX",
};
